/*
 * Copyright 2013 JavaANPR contributors
 * Copyright 2006 Ondrej Martinsky
 * Licensed under the Educational Community License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.osedu.org/licenses/ECL-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an "AS IS"
 * BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

package net.sf.javaanpr.gui.windows;

import java.awt.*;

public class FrameComponentInit extends javax.swing.JFrame {
    static final long serialVersionUID = 0;

    /**
     * Creates new form FrameComponentInit.
     */
    public FrameComponentInit() {
        this.initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int width = this.getWidth();
        int height = this.getHeight();
        this.setLocation((screenSize.width - width) / 2, (screenSize.height - height) / 2);
        this.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed"
    // desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        this.label = new javax.swing.JLabel();

        this.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        this.setTitle("Initializing system logic");
        this.setAlwaysOnTop(true);
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        this.setFocusable(false);
        this.setResizable(false);
        this.setUndecorated(true);
        this.label.setFont(new java.awt.Font("Arial", 0, 14));
        this.label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        this.label.setText("Starting application, please wait ...");
        this.label.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this.getContentPane());
        this.getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(this.label,
                org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE));
        layout.setVerticalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(this.label,
                org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE));
        this.pack();
    } // </editor-fold> //GEN-END:initComponents

    // Variables declaration - do not modify //GEN-BEGIN:variables
    private javax.swing.JLabel label;
    // End of variables declaration //GEN-END:variables

}
